version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
        - "furo"
        - "pyright"
        - "pytest-cov"
        - "pytest"
        - "PyYaml"
        - "sphinx_design"
        - "sphinx-autobuild"
        - "sphinx-vhs"
        - "sybil"
        - "toml"
        - "typing_extensions"
      style:
        patterns:
        - "pre-commit"
        - "ruff"
